# Generated by Django 3.1.7 on 2021-03-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210324_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=200)),
                ('headline', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
