# Generated by Django 3.1.7 on 2021-04-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_gamereview_storyline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamereview',
            old_name='content',
            new_name='content_block1',
        ),
        migrations.AddField(
            model_name='gamereview',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='concept',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='content_block2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='content_block3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='developer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='entertainment_value',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='header',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='media_block1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='media_block2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='platforms',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='playability',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='publish_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='publisher',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='replay_value',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='reviewed_on',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='sound',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gamereview',
            name='visuals',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gamereview',
            name='first_release_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='gamereview',
            name='game_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gamereview',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gamereview',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
