# Generated by Django 3.1.7 on 2021-04-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210407_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamereview',
            name='cover',
            field=models.URLField(null=True),
        ),
    ]
